version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
  
  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

