name: Deploy Laptop Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload frontend to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./frontend

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

