name: Build, Test, Deploy

on:
  push:
    branches:
      - master
      
permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Backend Docker Image
      run: docker build -t laptop-backend ./backend

    - name: Run Backend Tests
      run: docker run laptop-backend npm test

  deploy-frontend:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload frontend to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./frontend

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4


